//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APisuphero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heroes_Misiones
    {
        public int IDHeroe { get; set; }
        public int IDMisiones { get; set; }
        public Nullable<System.DateTime> Fechaasig { get; set; }
    
        public virtual Misiones Misiones { get; set; }
        public virtual SuperHeroe SuperHeroe { get; set; }
    }
}
