//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APisuphero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heroe_Poder
    {
        public int IDPoder { get; set; }
        public int IDHeroe { get; set; }
        public Nullable<double> Nivel { get; set; }
    
        public virtual Poder Poder { get; set; }
        public virtual SuperHeroe SuperHeroe { get; set; }
    }
}
